### ISSUE TITLE
The target setting doesn't seem to work

### ISSUE THREAD

**Issue by kainam00** [CenterForAssessment/atom-gist-dev#4] opened 2015-08-04 17:27 UTC
It defaults to /tmp regardless of what is set in the target directory box. 

OSX 10.10.4
Atom 1.0.3

**Comment by bclinkinbeard** [comment] 2015-08-04 23:37
Yea, I think I have an issue logged for this already. There are permissions issues with other locations and I haven't had time to troubleshoot yet.

**Comment by bclinkinbeard** [comment] 2015-08-05 13:58
Duplicate of #1

**Closed by bclinkinbeard** 2015-08-05 13:58 UTC
